React 19 integration fixes
ckeditor/ckeditor5-react pull request #480
Opened 2024-05-20 10:01 UTC by Mati365

### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Fix React 19 crashes. Closes https://github.com/ckeditor/ckeditor5-react/issues/478

2024-05-28 10:25 UTC, Mati365 commented
No regressions according to QA [testing results](https://cksource.slack.com/archives/C04VC9FK5LJ/p1716888581538939?thread_ts=1716378172.304639&cid=C04VC9FK5LJ).

2024-05-28 12:15 UTC, Mati365 commented
Do not rebase.

2024-05-29 11:27 UTC, Mati365 commented
Note after call: It'll be merged _after_ new installation methods.

2024-06-05 10:37 UTC, Mati365 commented
PR should now work with new installation methods

2024-06-06 11:54 UTC, Mati365 commented
@f1ames Can you take a look at this PR? I've heard that you worked with React before, it'd be nice to hear additional feedback about changes. Thanks!

2024-06-07 08:50 UTC, DawidKossowski requested changes
Several additional things that I found:

1. Unit tests produce a lot of errors in the console:
![Zrzut ekranu 2024-06-7 o 10 06 48](https://github.com/ckeditor/ckeditor5-react/assets/20561161/a39d9dee-b34a-482c-ab81-23574e394d7b)
Is it the desired behavior?

2. I got this error once in the Context demo (React 19):
![Zrzut ekranu 2024-06-7 o 10 41 58](https://github.com/ckeditor/ckeditor5-react/assets/20561161/9a63e747-e4d6-4060-9bc4-bbb7bc45d8ce)
However, I am no longer able to reproduce it. I believe there is still a possibility of a race condition. Perhaps we should invest more time in testing and debugging it.

3. The `isLayoutReady` prop in `CKEditorContext` works differently in the "classic" integration and multi-root integration. After providing `isLayoutReady={false}` in `demo-multiroot-react-19`, roots are rendered, and you can edit the content. However, when you pass the same prop in `demo-react-19`, the editor is not shown.

4. Generally, I understand it was a good opportunity to refactor some code, but adding new functionalities made the overall changes unclear. I'm not sure which changes were necessary in the context of supporting React 19 and which were made for refactoring purposes. I believe we could have done it in two steps. Additionally, I need to rethink the additional types, guards, and so on.

2024-06-07 08:50 UTC, DawidKossowski commented on src/useMultiRootEditor.tsx
> +				ui.view.removeEditable( rootName );
I think you could use `editor.detachEditable` instead.

2024-06-07 09:41 UTC, Mati365 commented on demo-react-19/src/ContextDemo.tsx
> +			{ /* @ts-expect-error: Caused by linking to parent project and conflicting react types */ }
It is still required, as it was mentioned in comment the react types are conflicting.

2024-06-07 12:20 UTC, Mati365 commented
@DawidKossowski 

> Unit tests produce a lot of errors in the console

It happens when CKEditor has roots that are not assigned to DOM while being destroyed. Happens frequently in `renderHook` test suite. I added fake elements before destroying editor to prevent this situation ([commit](https://github.com/ckeditor/ckeditor5-react/pull/480/commits/6b114d7a74887f6c658fcfd0b90ed4a513d61063)). Overall I think it's not super crucial and maybe useful in testing only. 
  
> I got this error once in the Context demo (React 19):

I cannot reproduce this race condition altough I believe that you are right. There can be race condition between synchronization of watchdog state and React state. Basically context might be destroyed and react state update (about reinitialization of such react context) is still pending while editor is initializing. I pushed [commit](https://github.com/ckeditor/ckeditor5-react/pull/480/commits/8d1cdcbe9a580e830e9844127d6dffcbf816f95e) that fixes the issue I think.

> The isLayoutReady prop in CKEditorContext works differently in the "classic" integration and multi-root integration. After providing isLayoutReady={false} in demo-multiroot-react-19, roots are rendered, and you can edit the content. However, when you pass the same prop in demo-react-19, the editor is not shown.

Is it correct behavior? It looks like our current implementation is broken (or it has another race condition). It makes absolutely no sense to initialize any editor within `ContextProvider` without waiting for initialization of context (because it will fall into the context adapter fallback in [these](https://github.com/ckeditor/ckeditor5-react/blob/ck/478/src/ckeditor.tsx#L225-L235) lines).

> Generally, I understand it was a good opportunity to refactor some code, but adding new functionalities made the overall changes unclear. I'm not sure which changes were necessary in the context of supporting React 19 and which were made for refactoring purposes. I believe we could have done it in two steps. Additionally, I need to rethink the additional types, guards, and so on.

Generally speaking it's complicated because it solves complex problem. React 19 tends to be more async than any other previous release and it only shown us hidden for many years issues with our implementation. The example might be `async` lifecycle methods in context class component which were reported already by community. These methods added other smaller race conditions. `StrictMode` another ones. `null` value in default context value too. This PR fixes all these smaller things to fix "big" Race Condition issue. 

> I believe we could have done it in two steps.

Agree however this PR is the first step. The next ones should be related to DX improvements and should utilize newer react hooks such as https://react.dev/reference/react/useSyncExternalStore which might help us with fixing with that kind of race condition issues (I hope so at least).

2024-06-10 12:19 UTC, Mati365 commented
Probably fixes this issue https://github.com/ckeditor/ckeditor5-react/issues/485#issue-2343726122. Must be checked.

2024-06-10 12:24 UTC, Mati365 commented
@Witoso  At this moment, nope. Too many changes. Initially, I thought that the watchdog race conditions were only reproducible on React 16-18. However, it turns out that they can also occur occasionally on older versions. On React 19, these race conditions happen consistently.

2024-06-10 12:27 UTC, Witoso commented
Hmm, will it mean that context in next.js won't work until we release this PR?

2024-06-10 13:39 UTC, f1ames commented
> @Witoso I suspect that it's reproducible on old installation methods, actually. Needs to be verified.

Yes, I checked with old installation methods and stable `ckeditor5-react` package and there is the same issue as reported in #485 for NIM setup.

2024-06-12 11:57 UTC, DawidKossowski commented
> Generally speaking it's complicated because it solves complex problem.

@Mati365, sure, the problem is complex, and it is understandable. However, you have exported a lot of new things as a public API. Who should use it and when? We need to provide user guides describing the correct use cases and so on.

Moreover, we still want to refactor the whole integration. In that case, the public API could change. I would rather reduce the breaking changes in the future by only making internal changes that fix the issue instead of extending the API. That is what I meant.

2024-06-12 12:04 UTC, Mati365 commented
@DawidKossowski I thought it may be useful [here](https://github.com/ckeditor/ckeditor5-react/issues/409). I don't think that context format will be changed in future iterations so much. If you think we should not export it, I'll remove it.

2024-06-12 12:35 UTC, DawidKossowski commented
That's what I meant by doing it in two steps. The first step will fix the integration with React 19 internally (the current PR), and the second step will enhance DX, the public API, and so on. I think the second step should be done as a separate task since it requires some research, analysis, and probably discussion. I'm not 100% sure about the current shape, and I don't want to block this PR, so I would remove it and address it in another task.

2024-06-12 12:36 UTC, Mati365 commented
@DawidKossowski gotcha, will be removed

2024-06-14 07:23 UTC, DawidKossowski approved these changes

2024-06-18 08:46 UTC, DawidKossowski commented
I will merge it after releasing NIM.

2024-06-26 13:27 UTC, merged

2024-06-26 13:29 UTC, Witoso commented
BTW, [React 19 is delayed.](https://www.cloudways.com/blog/react-v19-delay-suspense-tag-controversy/)